### ISSUE TITLE
How to integrate netlify-cms-widget-mdx

### ISSUE THREAD

**Issue by jethar** [delucis/astro-netlify-cms#19]
This is a very useful starter. One thing which I am not able to figure out is how to integrate [`netlify-cms-widget-mdx`](https://www.npmjs.com/package/netlify-cms-widget-mdx)

Being able to support **mdx widget** (in place of markdown) would be very useful.

Basically where and how to add the following lines:

```javascript
import { MdxControl, MdxPreview } from 'netlify-cms-widget-mdx';

CMS.registerWidget('mdx', MdxControl, MdxPreview);
```

**Comment by delucis** [comment]
Hi @jethar! This isn’t currently supported although I would like to. I’m already tracking this feature in #9 if you want to subscribe for updates.

I’ll close this as a duplicate and we can continue discussion on the existing issue.
