### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by ddorstijn** [delucis/astro-netlify-cms#43]
I was wondering if it was possible to use this with i18n support. Is there an example? Would it be possible to combine with a multilingual front page? Or do you need a different package for multilanguage options for the front page like 18next?

**Comment by delucis** [comment]
Should be possible with Netlify CMS's i18n settings! I don't have an example to hand but their docs are here: https://www.netlifycms.org/docs/beta-features/#i18n-support

**Comment by ddorstijn** [comment]
You are right. I realize this issue is out of scope for this project. Thanks for your answer
