### ISSUE TITLE
Creating a collection for global/page-specific settings

### ISSUE THREAD

**Issue by samhenrigold** [delucis/astro-netlify-cms#59]
I've just started playing with this integration today and I'm running into a bit of a project design issue. If I wanted to add a collection to NetlifyCMS to use as feature switches (e.g. "show author names on blog landing page"), how should I go about building that so I can read that value in my Astro file and change the page accordingly? I'm still exploring Astro, I don't have any pre-existing file structure to worry about so I'm open to any suggestions.

When I was using 11ty, I would just create a blogSettings.yml file and read directly from that since it gets supplied as global data. I'm not sure what the proper style here would be.

Thanks for your help, appreciate the work you're doing!

**Comment by delucis** [comment]
My go-to for this is usually to store these as JSON as those are very easily imported into your Astro project.

Here’s a minimal example that stores `title` and `showAuthorNames` values in `src/settings/general.json`:

```js
import { defineConfig } from 'astro/config';
import NetlifyCMS from 'astro-netlify-cms';

export default defineConfig({
  integrations: [
    NetlifyCMS({
      config: {
        backend: {
          name: 'git-gateway',
          branch: 'main',
        },
        collections: [
          {
            name: 'settings',
            label: 'Site Settings',
            files: [
              {
                name: 'general',
                label: 'General',
                file: 'src/settings/general.json',
                fields: [
                  {
                    name: 'title',
                    widget: 'string',
                    label: 'Site Title',
                  },
                  {
                    name: 'showAuthorNames',
                    widget: 'boolean',
                    label: 'Show author names on landing page',
                  },
                ],
              },
            ],
          },
        ],
      },
    }),
  ],
});
```

Then in your Astro pages you can import this file and use its data:

```astro
---
// src/pages/index.astro

import { title, showAuthorNames } from '../settings/general.json';
---

<h1>{title}</h1>

{showAuthorNames && 'Toni Morrison'}
```

**Comment by samhenrigold** [comment]
Ah I didn't know Netlify can write to JSON, amazing! I'll give it a shot

**Comment by delucis** [comment]
Yeah, they actually support saving to a bunch of formats! https://www.netlifycms.org/docs/configuration-options/#extension-and-format

I'll close this for now as I don't think there's anything more that needs doing in this repo but feel free to ask any other questions if you run into issues.
