### ISSUE TITLE
When we hover over author in header section it turns to text cusor and author href doesn't work in header section

### ISSUE THREAD

**Issue by DenjixPochita** [delucis/astro-netlify-cms#6]
You can check it on https://randomname123.netlify.app/posts/
The problem is only in header section.

**Comment by delucis** [comment]
Thanks for the bug report! The URL prop wasn’t being passed to the Post component correctly. Fixed in 9728c7b2b5c8e7c2cb69b93d3206f1bc14c07656.

**Comment by DenjixPochita** [comment]
Owo that was super quick!
Thanks for the fix!
