### ISSUE TITLE
Undefined disableIdentityWidgetInjection causes script to be injected onto every page

### ISSUE THREAD

**Issue by christiankozalla** [delucis/astro-netlify-cms#60]
Hey there!

I've just noticed that a script `page.<hash>.js` is injected into every page when using this integration with the default config from the [Astro Netlify CMS Starter.](https://github.com/delucis/astro-netlify-cms-starter)

I'm unsure whether this is the desired behavior. I've read that the identity widget is used if you're hosting the blog+cms on Netlify and do not use a git hosting provider such as github. So `backend: git-gateway`, hosted on Netlify without github et al.

## Steps to reproduce
- Clone the Astro-Netlify-CMS-Starter: https://github.com/delucis/astro-netlify-cms-starter
- Build the project
- `cat dist/index.html | grep 'src="/page.'`` 

I'm opening this issue because I'm not sure if this is a bug or desired.
Thank you!

**Comment by delucis** [comment]
Hey! Yes this is the expected behaviour. If you want to disable the injection for whatever reason, you can set [`disableIdentityWidgetInjection: true`](https://github.com/delucis/astro-netlify-cms#disableidentitywidgetinjection) in the integration config object.
