### ISSUE TITLE
Netlify CMS doesn't work properly

### ISSUE THREAD

**Issue by DenjixPochita** [delucis/astro-netlify-cms#7]
I get CORS Missing Allow Header
https://clever-stroopwafel-5cf68a.netlify.app
And the admin panel doesn't work because of it.
The repo is untouched thank you!

**Comment by delucis** [comment]
Could you check if the latest commit fixes this for you? I hadn’t included the new `is:inline` directive on the script tag loading the Netlify Identity Widget and I think that was to blame.

**Comment by DenjixPochita** [comment]
Yup it's working fine!
Next time I will be the one to create PR if I found bugs 😅
Thanks again for the quick fix!
