### ISSUE TITLE
Update to Decap

### ISSUE THREAD

**Issue by OliverSpeir** [delucis/astro-netlify-cms#85]
here is a working fork

https://github.com/advanced-astro/astro-decap-cms

I have seen numerous people attempt to use this as it is linked in the docs but only to be confused 

If you're willing to keep this up to date, I am happy to update the demo

**Comment by delucis** [comment]
Hey @OliverSpeir are you interested in maintaining your fork? I haven't found time to maintain this, so would be happy to link there instead if you like! Alternatively, you could PR this project and we could update it. Not sure if there'd be any breaking changes, but at this point it does seem to be the way to go.

**Comment by OliverSpeir** [comment]
It's not actually my fork, I put a PR into it to see if they're still maintaining. It just needs the peer deps update for astro 4. 

I would be willing to maintain one, but astro-decap-cms is a nice npm name and since they've already done the work I will see if they are still maintaining it.

If they don't respond I'll PR to this repo and we can just stick with astro-netlify-cms
